services:
  - type: web
    name: live-cricket-simulator
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: RUN_JOBS
        value: true
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cricket-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: cricket-db
    databaseName: cricket
    user: cricket
    plan: free
    region: singapore
